### PR TITLE
Use a `sync.Map` in the `MockChain` and make all methods pass by reference

### LINKED ISSUE #730: `go test ./client_test -run TestDirectFund -race` FAILS

### PR DESCRIPTION
**Pull request by geoknee**
Closes #730

### CODE REVIEW

File: client/engine/chainservice/mockchain.go [hunk 1]
```diff
@@ -102,10 +107,10 @@ func (mc MockChain) handleTx(tx protocols.ChainTransaction) {
 		panic("unexpected chain transaction")
 	}
 
-	for _, out := range mc.out {
-		attemptSend(out, event)
-	}
-
+	mc.out.Range(func(key string, value chan Event) bool {
```
Comment (NiloCK) [inline client/engine/chainservice/mockchain.go:110]: nit: blank identifier makes the non-use explicit.

```suggestion
	mc.out.Range(func(_ string, value chan Event) bool {
```

**Review by NiloCK — APPROVED** [review]
LGTM.

Sadly, I still see the flicker locally with this branch, but these sorts of issues are definite suspects.
