### PR TITLE
fix typo

### LINKED ISSUE #869: fix this typo
https://github.com/statechannels/go-nitro/blob/e70703cba68dbd58922d95d80442121274bb03c7/protocols/virtualfund/virtualfund_test.go#L66-L67

### PR DESCRIPTION
**Pull request by geoknee**
closes #869

### CODE REVIEW

File: protocols/virtualfund/virtualfund_test.go [hunk 1]
```diff
@@ -63,7 +63,7 @@ func TestMarshalJSON(t *testing.T) {
 	encodedVfo, err := json.Marshal(vfo)
 
 	if err != nil {
-		t.Fatalf("error encoding direct-fund objective %v", vfo)
+		t.Fatalf("error encoding virtualfun objective %v", vfo)
```
Comment (NiloCK) [inline protocols/virtualfund/virtualfund_test.go:66]:
```suggestion
		t.Fatalf("error encoding virtualfund objective %v", vfo)
```

**Review by NiloCK — COMMENTED** [review]
:+1:

File: protocols/virtualfund/virtualfund_test.go (hunk 1 above)
Comment (geoknee) [reply protocols/virtualfund/virtualfund_test.go:66]: I'm glad you are here to police the police.
